### ISSUE TITLE
How to change the branch name when clicking ”Deploy”

### ISSUE THREAD

**Issue by ajmalafif** [sanity-io/sanity-plugin-dashboard-widget-netlify#12]
Hey team, 

How do I rename or change `production@head` to say `main@head` when I pressed this Deploy button?
<img width="618" alt="Screenshot 2021-03-30 at 10 11 35 PM" src="https://user-images.githubusercontent.com/827167/113003431-519ff180-91a5-11eb-8f9a-62930591275c.png">

**Comment by kendallroth** [comment]
This is a very valid question, especially with the recent commonality of changes from `master` to `main`

**Comment by kendallroth** [comment]
Just realized that you can change this by generating a _different_ build hook (for `main`) in the Netlify Continuous Deployment settings, then update your admin `dashboardConfig.js` to use the new build hook ID.

**Comment by ajmalafif** [comment]
thank you @kendallroth its all working now!
