### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [sanity-io/sanity-plugin-dashboard-widget-netlify#2]
I'd love to fork this as a basis for a similar non-Netlify integration (possibly too specific to be useful to anyone else).

So far as I've spotted, all I have to go on for the license is the `package.json` MIT declaration.

Please would you consider adding a LICENSE file to this repository? Thank you.

**Comment by kmelve** [comment]
Done! Feel free to fork – and I look forward to seeing what you're doing with it 👍
