### ISSUE TITLE
Typescript file not found

### ISSUE THREAD

**Issue by dmorda** [sanity-io/sanity-plugin-dashboard-widget-netlify#5]
I noticed the following file was expected to be there, but VSCode is outputting the following error:

`File '<path to install>/studio/node_modules/sanity-plugin-dashboard-widget-netlify/dist/types/sanity-plugin-dashboard-widget-netlify.d.ts' not found.`

**Comment by rexxars** [comment]
Should hopefully be fixed in [v1.1.0](https://github.com/sanity-io/sanity-plugin-dashboard-widget-netlify/releases/tag/v1.1.0), thanks for reporting
